# This is example micrit config.
# File needs to be created in /etc/micrit.conf

# udev daemon. default value is "/usr/lib/systemd/systemd-udevd" (default systemd-udevd binary location in Gentoo Linux)
UDEV_DAEMON=/usr/lib/systemd/systemd-udevd
# hostname. default value is "localhost"
HOSTNAME=micrit
# interfaces. means inet interfaces that are needed to be set up on boot (excluding loobpack (lo)). default values are "". can contain multiple values
INTERFACES=wlan0 eth0
